name: debian
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: git fetch origin +refs/tags/*:refs/tags/*
    - name: debian.sh
      run: |
        .github/workflows/debian.sh ci
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "out/*"
        token: ${{ secrets.GITHUB_TOKEN }}