name: debian
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install git
    - run: git fetch origin +refs/tags/*:refs/tags/*
    - name: Release
      run: |
        .github/workflows/release.sh ci
