name: docker-release-assets
on: push
jobs:
  debiab-buster:
    runs-on: ubuntu-latest
    container: debian:buster
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    steps:
    - name: Upgrade the packages
      run: apt-get update && apt-get upgrade -y && apt-get install -y git 
    - uses: actions/checkout@v2
    - name: build
      run: .github/workflows/debian-release.sh
    - name: upload the assets
      run: .github/workflows/upload-release-assets.py