name: docker-release
on: push
jobs:
  debiab-buster:
    runs-on: ubuntu-latest
    container: debian:buster
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Upgrade the packages
      run: apt-get update && apt-get upgrade -y && apt-get install -y git 
    - uses: actions/checkout@v2
    - name: build
      run: .github/workflows/release.sh
    - name: upload the assets
      run: .github/workflows/assets.py
  debiab-bullseye:
    runs-on: ubuntu-latest
    container: debian:bullseye
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Upgrade the packages
      run: apt-get update && apt-get upgrade -y && apt-get install -y git 
    - uses: actions/checkout@v2
    - name: build
      run: .github/workflows/release.sh
    - name: upload the assets
      run: .github/workflows/assets.py